### ISSUE TITLE
Change the ownership of a wolf

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Sophisticated-wolves#15]
@lcherbst request:

Is it possible to add a feature where you could change the ownership of a wolf? I play on a private server with my two sons and I have 6 wolves. I would like to be able to give my sons a couple wolves each. Of course, with sophisticated wolves installed, they have a better chance at finding their own now anyway.

**Comment by DanTheColoradan** [comment]
A simple start would be a recipe for a "wild dog treat" that un-tames them.

Further along, how about it's like horses, so they are tamed with the cookie but don't do much else other than growl, prowl, and not attack if they are hit. Then, if you put a collar on them, they become yours. If you remove the collar, they go back to tamed but not owned mode?

**Comment by NightKosh** [comment]
Will be implemented in https://github.com/NightKosh/Sophisticated-wolves/issues/27
