### ISSUE TITLE
[Idea] Generalize sophisticated-wolves to sophisticated animals

### ISSUE THREAD

**Issue by DanTheColoradan** [NightKosh/Sophisticated-wolves#16]
I was starting to work on a mod that would add something like sophisticated horses, but I think I would be duplicating a lot of your code.

I haven't dug into your code yet, so it might be close already. But if not, would you accept a pull request that separates the wolf entity class from things we would want from horses as well?

For example, I would like for the horses to be able to teleport on drowning. So if I can, I could just use a sophisticated-animal base class and then build the special horse parts around that.

**Comment by NightKosh** [comment]
Sorry for so late reply. I guess this request is not actual for you anymore?

**Comment by DanTheColoradan** [comment]
No worries! Life gets crazy.

It's been a while since I've played. I plan to sometime soon. If you want, you can close this :) I'll ask ya to open it if I get back into MC again soon.

🍻

**Comment by NightKosh** [comment]
Thank you for understanding. Give me to know if you'll need anything.
