### ISSUE TITLE
Dog feed themselves?

### ISSUE THREAD

**Issue by daschmitz** [NightKosh/Sophisticated-wolves#21]
After a dog saves me from a zombie, it would be nice if it could go ahead and seek out and eat the rotten flesh dropped, rather than me having to go pick it up and then feed it to the animal.  There's a weird bug (I believe in either forge or minecraft) where if my hunger is down, I'll accidentally eat what I'm feeding to an animal.  This has happened with pigs, but also with my feeding rotten flesh to dogs, which, when this bugs rears its ugly head, makes me sick.

Just a thought...

**Comment by NovaViper** [comment]
Hey, Night, whenever you get the chance, you should look at [ProPercivalalb's Doggy Talents](https://github.com/ProPercivalalb/DoggyTalents). I do remember this mod allowing the dogs to automatically eat out of its dog bowl whenever it was hungry/low on health. The only thing is the guy hasn't updated to the latest so there are some changes to be made to it for 1.9+

**Comment by NightKosh** [comment]
@NovaViper I'm working on such feature now( #7 )
