### ISSUE TITLE
Crash: java.lang.NullPointerException: Ticking entity

### ISSUE THREAD

**Issue by fissionblue** [NightKosh/Sophisticated-wolves#24]
3 wolves present; 2 in follow mode and 1 in stay mode. No mobs or other interactions with wolves that I can tell of.

Full crash report is as follows:
http://pastebin.com/pLHUdTtr

Let me know if there is anything else I can do to help.

**Comment by NightKosh** [comment]
Hello. Unfortunately I can't reproduce this issue. But I made few fixes so it must be fixed as i hope. Try it please https://github.com/NightKosh/Sophisticated-wolves/releases/download/1.10.2/SophisticatedWolves-3.6.4.jar

**Comment by fissionblue** [comment]
Thanks for your response. To be frank, I can't reproduce it either now. Whatever the issue was, it is no longer happening on the newest Forge. (ending in 73). I'll keep an eye out for anything that might hint at any connections.
