### ISSUE TITLE
[Feature] Change spawning rate of wolves

### ISSUE THREAD

**Issue by NovaViper** [NightKosh/Sophisticated-wolves#26]
Hey, I've been using the mod for a while now and I'm wondering if you could add the ability to modify the spawning rate of the wolves? Or add a sort of tool that can attract nearby wolves

**Comment by NightKosh** [comment]
This feature will be implemented in next version of the mod, which will be done in a few days.
Furthermore I'm planning to add a new villager(#33) in the feature(it will not be in the next version), which will sell pet carriers with pets inside of it, so it will be easier to get dogs and cats.
