### ISSUE TITLE
Compatibility with "Wolf Armor and Storage"

### ISSUE THREAD

**Issue by raspopov** [NightKosh/Sophisticated-wolves#28]
Is it possible to make this mod compatible with "[Wolf Armor and Storage](https://mods.curse.com/mc-mods/minecraft/253689-wolf-armor-and-storage)" mod?  I'd like to have both, please...

**Comment by CovertJaguar** [comment]
The latest version of Wolf Armor and Storage sports compatibility.

**Comment by raspopov** [comment]
Where? I see no new releases since Jan 2017.

**Comment by CovertJaguar** [comment]
https://minecraft.curseforge.com/projects/wolf-armor-and-storage/files/2372932
