### ISSUE TITLE
Log spam

### ISSUE THREAD

**Issue by CovertJaguar** [NightKosh/Sophisticated-wolves#29]
It constantly spams the log in MP with:
```
java.lang.ClassCastException: com.google.common.base.Absent cannot be cast to java.lang.Integer
    at sophisticated_wolves.entity.EntitySophisticatedWolf.getSpecies()
```

**Comment by NightKosh** [comment]
Could you please post here your minecraft version and mod version?

**Comment by CovertJaguar** [comment]
Oops, MC 1.10.2 and 3.6.5

**Comment by NightKosh** [comment]
Unfortunately I can't reproduce this issue, like your another bug report( #14) . 
I just can suggest that this is a result of some kind of compatibility issue, or, maybe data corruption(or both of them together).
