### ISSUE TITLE
Config for dogs auto eating meat/rotten flesh.

### ISSUE THREAD

**Issue by 63502** [NightKosh/Sophisticated-wolves#34]
Could you please do this? Of all the features this mod adds, this is the only one I do not like. It is extremely annoying to try to use dogs to hunt zombies and passive mobs early-game, only to have them eat all the most important drops as soon as the make a kill.

**Comment by NightKosh** [comment]
Hello. It was planned for next update.

**Comment by 63502** [comment]
Ok, cool.
