### ISSUE TITLE
Food GUI and bowls are broken

### ISSUE THREAD

**Issue by Liberage** [NightKosh/Sophisticated-wolves#44]
I downloaded this mod from 9minecraft and it was broken (the "food select" gui was overlapping and unfunctional) bowls are, aswell, broken.
Now i tried downloading it from curse and i'll see if it's functioning.
Great mod, by the way

**Comment by NightKosh** [comment]
I never uploaded it to 9minecraft, so I don't know what exactly you got. 
So "curse" version is it ok?

**Comment by Liberage** [comment]
@NightKosh So! the bowl works, gui still broken.

**Comment by NightKosh** [comment]
Sorry, but not yet. I haven't got a free time now. I'll try to check it at the weekends.

**Comment by Liberage** [comment]
Also please separate the rotten flesh from the bone

**Comment by Liberage** [comment]
No worries
