### ISSUE TITLE
Lost my dogs to the Nether

### ISSUE THREAD

**Issue by Geethebluesky** [NightKosh/Sophisticated-wolves#53]
Whenever wolves manage to go across a portal to the Nether, they are transported there... without me. Both my dogs are stuck in the Nether now, and having them step into the portal again does nothing.

Is there another way to get the dogs back?

Using SophisticatedWolves-1.12.2-3.13.3.jar

**Comment by NightKosh** [comment]
I do nothing special with portals, so it should works in the same way as vanilla wolves.

You can craft "pet carriers" and place your dogs inside it to transport them anywhere you want.
