### ISSUE TITLE
Wolves not spawning (Except for Vanilla)

### ISSUE THREAD

**Issue by TheLunarArtemis** [NightKosh/Sophisticated-wolves#54]
So, I have a world with these mods: (No longer using Howling Moon, actually. Every mod except for Howling Moon is being used rn) 
![mods](https://user-images.githubusercontent.com/17260497/41947619-6c117f46-796d-11e8-874c-4e6d13b05aee.png)
and no brown or dark brown wolves are spawning in forest, or the white and black wolves spawning in taigas. I've found a few vanilla wolves, but no sophisticated ones, so I turned those into sophisticated by feeding them the dog treat, but it frustrates me because I want more than the white wolves....
I originally thought maybe the problem was Silent's Gems because of the glow-rose (Because i found somewhere on the curse forge that wolves wont spawn in light levels over 5), but I had removed all the glow-roses from about a quarter of my nearby taiga biome, and half of my nearby forest biome. 
Still after about 10 in game nights, no wolves are spawning, at all. Have only found one VANILLA wolf in that time span. 
Help??!!?

**Comment by TheLunarArtemis** [comment]
Oh, I forgot to add. I had set the spawn probability to 100 as well in the config during the time i removed the glow roses., but still nothing

**Comment by NightKosh** [comment]
Its color depends on biome in which it was spawned/transformed, and have a
chance(black and brown much rare then other colors). Also you can buy one
at special villager - pet seller. As for spawn - may be " RespawningWolves"
option set to false?(in this case wolves will not be spawned at all). Also
light level requirment was removed.

ср, 27 июн. 2018 г., 4:24 TheLunarArtemis <notifications@github.com>:

**Comment by V10lator** [comment]
Same issue here. Buying is no option as the special villager doesn't spawn, too. Config options are fine.

Seeing the above mod list we both have these mods:

- CustomMobSpawner
- DrZharks MoCreatures Mod
- Hwyla
- jei
- Pam's+HarvestCraft

**Comment by adrian154** [comment]
@NightKosh I see you added the "can't reproduce" label; did you try running with the same mods as @V10lator and @TheLunarArtemis? Maybe mod inter-compatibility is a problem; just a thought :)

Thanks

**Comment by V10lator** [comment]
@adrian154 Do/did you use CustomMobSpawner? It's just a shoot into tge blue but I know oft other mods that had issues with it untill they added compatibility...
