### ISSUE TITLE
Texture Pack not Texturing wolves?

### ISSUE THREAD

**Issue by tetsune** [NightKosh/Sophisticated-wolves#63]
I've replaced every texture with my Texture Pack, but for some reason Sophisticated Wolves (I have a tamed one in-game at the moment) are not textured by my pack.
I've seen some wild ones with the textures (there were some black ones I saw). I also have Vanilla wolves textured with a texture pack.

**Comment by NightKosh** [comment]
could you please provide more information about your texture pack, or may be post link on it?
