### ISSUE TITLE
[SUGGESTION/COMPAT] Registering entities in preinit and not init

### ISSUE THREAD

**Issue by itsmeow** [NightKosh/Sophisticated-wolves#66]
I am contributing to a mod that changes models from vanilla to higher detail and while working on compat for this mod I discovered that when I overwrite the renderer nothing happens because I am using preinit (as is the suggested stage by forge themselves) and this mod uses init to register entities. Entities should always be registered (as well as their renderers) in preinit.

Is there a specific reason to doing this the way it is?

**Comment by itsmeow** [comment]
I have gotten it to work fine by using postinit - but it just feels wrong.

**Comment by NightKosh** [comment]
Ok. I'l do it.

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/sophisticated-wolves/files/2628601
