### ISSUE TITLE
Dog bowl

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Sophisticated-wolves#7]
Add a dog bowl which will be used by dogs to eat. It will allow dogs to heal it self at home(if there are some meat in bowl)

**Comment by DanTheColoradan** [comment]
Are you thinking of using the vanilla bowl as the model?

**Comment by NightKosh** [comment]
@DanTheColoradan  No

![Dog Bowl model](http://i.imgur.com/VHJ7CCA.png)
