### ISSUE TITLE
Crash with Dog bowl (Incompatible with other mod's chests)

### ISSUE THREAD

**Issue by SeanChengN** [NightKosh/Sophisticated-wolves#70]
First, It's not same as this issue: https://github.com/NightKosh/Sophisticated-wolves/issues/50#issue-306164549

**To Reproduce**
Place dog bowl and destroy it, then place other chests and open it.

**Test three mods for example**
1.Crash with [Pam's HarvestCraft](https://minecraft.curseforge.com/projects/pams-harvestcraft)
![sw-phc](https://user-images.githubusercontent.com/20624068/47282994-e9cc4080-d613-11e8-89be-6aec18fc1266.gif)
Crash Report: https://pastebin.com/yCDgSn0s

2.Crash with [MrCrayfish's Furniture](https://minecraft.curseforge.com/projects/mrcrayfish-furniture-mod)
![sw-mcf](https://user-images.githubusercontent.com/20624068/47283145-9c040800-d614-11e8-961a-654767c2f1d2.gif)
**At the same time, the position of the items has been changed.**
Crash Report: https://pastebin.com/9KzgCSF8

3.Crash with [Enchanting Tweaks](https://minecraft.curseforge.com/projects/enchanting-tweaks)
![sw-et](https://user-images.githubusercontent.com/20624068/47283229-fd2bdb80-d614-11e8-9560-96c66c49efa8.gif)
Crash Report: https://pastebin.com/zEfcXzLD

**Mod Version**
Forge: 1.12.2-14.23.5.2768
SophisticatedWolves: 3.13.6
Pam's HarvestCraft: 1.12.2za
MrCrayfish's Furniture: 5.15.0
Enchanting Tweaks: 1.0

**Comment by NightKosh** [comment]
https://minecraft.curseforge.com/projects/sophisticated-wolves/files/2632741
