### ISSUE TITLE
Feature request: Whitelist/blacklist for creatures the pet carrier can/cannot pick up

### ISSUE THREAD

**Issue by Febilian** [NightKosh/Sophisticated-wolves#75]
I just had a player on my server lose a baby Ice and Fire dragon because they can't get it out of the pet carrier, and while that's another issue I'll bring up when I have replicated it with logs, it'd be nice to have the option to flat-out prevent select mobs from being picked up, just to be safe.

**Comment by NightKosh** [comment]
There aren't any needs in it. Pet carrier already should be available only for special list of creatures:  wolves, sophisticated wolves, cats, chickens, rabbits & parrots. Any modded mobs should not be catched without mod support. So you "catch a bug".
