### ISSUE TITLE
Mob ID for wolf includes a path.

### ISSUE THREAD

**Issue by frakier** [NightKosh/Sophisticated-wolves#77]
I need to add the sophisticated wolves id to a list.
This is also required in the /summon command.

This is the value in BabyMobs-1.12-1.5.5
sophisticatedwolves:textures/entity/brown/wolf.png

should probably be [or something similar]
sophisticatedwolves:wolf

**Comment by NightKosh** [comment]
Hello. This is a know bug. But unfortunately it will not be fixed in the nearest time because of backward compatibility - all existed wolves will be missed in case of its change. So it will be fixed  only for next minecraft version
