### ISSUE TITLE
Spam Spawning

### ISSUE THREAD

**Issue by Thethuthinnang** [NightKosh/Sophisticated-wolves#78]
I lowered the spawn rates from the default configuration to the following values:

    I:SpawnMaxCount=3
    I:SpawnMinCount=1

    I:SpawnProbability=2

Yet the spawning does not seem to be affected. I started a world with the default config, then saw the spawning and recreated the world from the seed after adjusting the config file, but I saw the same spawning. The sheer volume of the wolves is such that it effectively eliminates any other passive/neutral mob spawning in the area. The FPS also dramatically drops.

![2019-03-30_02 47 51 sophisticated wolves spawning](https://user-images.githubusercontent.com/47260138/55273215-84e9d600-5296-11e9-962f-bd2c34cf669c.png)
(The neon green mass on the minimap is also the wolves; the map had trouble tracking them all and stopped registering the closest ones as I moved closer to this little area.)

I appreciate and am excited for the concept of this mod, and I want to use it, but the spawning is out of control and doesn't seem config-responsive. I would appreciate any help.

**Comment by BritishMindslave** [comment]
I'm also having the same issue. My spawning config is on the default 5, and yet I have a million brown wolves running around my meadow. xD;
(Have you heard that many wolves shake off rain? <i>It's constant.</i>)

I'm using the latest version of the mod - 3.13.7 - for 1.10.2

**Comment by akharding91** [comment]
I'm also having the same problem as both Thethuthinnang & BritishMindslave. I'm using SophisticatedWolves-3.13.8 with forge-14.23.5.2838

I did test to see if this error only happens with SophisticatedWolves installed and found that it doesn't. so it must be conflict with another mod installed, I'm going to continue testing and I'll report back with my findings.

**Comment by akharding91** [comment]
Okay, not sure if this Thethuthinnang & BritishMindslave problem but the mod conflict for me is between SophisticatedWolves and [Charm](https://www.curseforge.com/minecraft/mc-mods/charm) mod. 

Pictures below are in a flat taiga 4x4 chunk world boarder world. I used the command /kill @e[type=!Player] to remove all mobs except the ones in the 4x4 chunk area 

Both test were done after loading the world, using the /kill @e[type=!Player] command, and waiting about 2 minute.

With both SophisticatedWolves & Charm Installed
![SO And CHARM](https://user-images.githubusercontent.com/29419588/61974505-9076b080-af9b-11e9-9aae-6c6a5fa5e87a.png)

With only SophisticatedWolves installed
![SO ONLY](https://user-images.githubusercontent.com/29419588/61974775-31656b80-af9c-11e9-9262-55269486cbad.png)
