### ISSUE TITLE
Parrot Pet Carrier Glitch (Visual)

### ISSUE THREAD

**Issue by PiordaNautor** [NightKosh/Sophisticated-wolves#85]
If you put a Parrot in a Pet Carrier while they're sitting, and then release the Parrot, the Parrot will not change from it's Sitting Animation until you tell the Parrot to "Sit" and "Unsit" (or presumably after having them perch on you).

**Comment by NightKosh** [comment]
Could you please provide additional information(and a few screenshots if possible).  Unfortunately I can't reproduce this problem.
