### ISSUE TITLE
whistle

### ISSUE THREAD

**Issue by NightKosh** [NightKosh/Sophisticated-wolves#9]
When it will be used all dogs in some range will be teleported to its owner.

**Comment by DanTheColoradan** [comment]
![whistle](https://cloud.githubusercontent.com/assets/3826143/9287246/815435b2-42c8-11e5-9833-4878597dd8ed.png)

[Xun] https://en.wikipedia.org/wiki/Xun_(instrument))

**Comment by DanTheColoradan** [comment]
I've started the changes for a whistle at my [fork](https://github.com/DanTheColoradan/Sophisticated) on the "feature/whistle" branch.

**Comment by NightKosh** [comment]
@DanTheColoradan Thank you for texture, but I prefer to use more common type of  whistle. Unfortunately it is not obvious what is on those image(for most people)
