### ISSUE TITLE
[1.19.2] Cannot start server with the mod

### ISSUE THREAD

**Issue by NerineHub** [NightKosh/Sophisticated-wolves#94]
Hello! Whenever I try to start Athernos server with the mod, it crashes. I really love the mod and it's idea though. Server is on Forge 1.19.2 (43.1.52). All of the other mods seem to work pretty fine on the server. 

The version that I have installed: Sophisticated_Wolves-4.0.0b1.jar

I am able to launch Minecraft instance on my device, it loads correctly.

Would also love to see wolves carry a backpack and armour of some sort!

**Comment by DashieDev** [comment]
https://github.com/NightKosh/Sophisticated-wolves/commit/3ae20eed21c7b2637a4781b951cfe268faf4e293#r89518233

**Comment by DashieDev** [comment]
Fixed. You can confirm it by retry it on the server.

**Comment by NightKosh** [comment]
https://www.curseforge.com/minecraft/mc-mods/sophisticated-wolves/files/4077244

**Comment by NerineHub** [comment]
yes, now I can launch the server, thank you
